# Generated by Django 5.0.4 on 2024-04-29 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('INV', 'Sale'), ('PO', 'Purchase')], max_length=4)),
                ('paid_through', models.CharField(choices=[('SH', 'Cash'), ('MM', 'M-Pesa')], max_length=4)),
                ('transaction_status', models.CharField(choices=[('CMP', 'Complete'), ('ICMP', 'Incomplete')], max_length=5)),
                ('transaction_party', models.CharField(max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_amount', models.FloatField(default=0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_affected', models.FloatField(default=1)),
                ('unit_price', models.FloatField()),
                ('transaction_value', models.FloatField(blank=True, null=True)),
                ('product_cost', models.FloatField(blank=True, null=True)),
                ('transaction_cost', models.FloatField(blank=True, null=True)),
                ('transaction_earnings', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Inventory.product')),
                ('accompanying_transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction', to='Transactions.transactionrecord')),
            ],
        ),
    ]
