# Generated by Django 5.0.4 on 2024-04-29 08:42

import Inventory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(default='XXX', max_length=100)),
                ('product_name', models.CharField(max_length=300)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=Inventory.models.product_image_path)),
                ('product_category', models.CharField(default='General', max_length=70)),
                ('product_quantity', models.FloatField(default=0)),
                ('product_unit', models.CharField(default='unit', max_length=200)),
                ('product_minimum_threshhold', models.FloatField(default=1)),
                ('product_stock_level', models.CharField(choices=[('BELOW_T', 'Below Threshhold'), ('LOW', 'Low Level'), ('NORM', 'Normal Level'), ('HIGH', 'High Level')], default='NORM', max_length=10, null=True)),
                ('product_selling_price', models.FloatField(default=0)),
                ('product_cost', models.FloatField(default=0)),
                ('product_date_added', models.DateTimeField(blank=True, editable=False, null=True)),
                ('product_date_modified', models.DateTimeField(blank=True, null=True)),
                ('product_last_stocked', models.DateTimeField(blank=True, null=True)),
                ('product_last_sold', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventory')),
            ],
        ),
    ]
